### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by DragonfireHD98** [ClickedTran/libRanks#1]
Can i use the virion  for pureperms and RankshopUI ?

**Comment by ClickedTran** [comment]
Your RankShopUI?
Sure, why not, just change `ranksystem` to `pureperms` or `pp` then you can use it

**Comment by ClickedTran** [comment]
If you have no other questions, I'll close this issue @DragonfireHD98 
If you still have questions, please open another issue
Also you can look at the <a href="https://github.com/ClickedTran/libRanks/wiki">wiki</a> to clearly understand how the lib works if you are a developer

Thank you so much!
